### ISSUE TITLE
How to connect behind a proxy

### ISSUE THREAD

**Issue by ralfrupf1976** [prrvchr/vCardOOo#2]
If I try to connect to my nextcloud to use vcard contacts as address base for writer it fails.

QL-Status: Authentication ERROR
Fehlercode: 1641

User xxxxx.xxxxxx with password ************** cannot connect to server cloud.xxx-xxxxxx.ch at URL http://cloud.xxx-xxxxxx.ch/remote.php/dav/

Is it beacause my cloud is only reachable via SSL - it seems that the extension connects via http

**Comment by prrvchr** [comment]
Hi ralfrupf1976,

> User xxxxx.xxxxxx with password ************** cannot connect to server cloud.xxx-xxxxxx.ch at URL http://cloud.xxx-xxxxxx.ch/remote.php/dav/

Normally if the server is configured correctly, in **Step 2 -> Connection setting -> General** only the server address is needed, which in your case would be: **cloud.xxx-xxxxxx.ch**

> Is it beacause my cloud is only reachable via SSL - it seems that the extension connects via http

The protocol does not have to be specified in **Connection setting -> General** but the connection will be made by default in https if available.

**Comment by ralfrupf1976** [comment]
I think that I configured everything right - just: cloud.xxx.xxxx.ch
but it always ends in the error above..

**Comment by prrvchr** [comment]
I am surprised by the messages that vCardOOo returns because `Fehlercode: 1641` is not a code coming from the extension.

If I try to connect with a faulty username or password I have the following message:

![User or password error](https://github.com/user-attachments/assets/4499ce4c-c3b6-4ac8-bf49-aa8c0a9f3a4d)

If I try to connect with a server name that is not accessible then I get the following message:

![Server error](https://github.com/user-attachments/assets/c462933c-51eb-41a3-95b2-8620727761b0)

I think the code `Fehlercode: 1641` comes from your server and in my opinion this requires verification.

**Comment by prrvchr** [comment]
For further investigation I have prepared a BASIC macro to test whether the server responds to a discovery url request.

```
Sub Main

    Rem First we need to create the UNO OAuth2Service without OAuth2
    oRequest = CreateUnoService("io.github.prrvchr.OAuth2OOo.OAuth2Service")
    Rem The OAuth2OOo extension is not installed!!!
    if isNull(oRequest) then
        Msgbox "You need to install the OAuth2OOo extension to use this macro!"
        exit sub
    endif

    Rem Ask the user for a NextCloud server address
    sServer = InputBox("Please enter a NextCloud server", _
                       "Test NextCloud Discovery URL")
    Rem User clicked Cancel
    if sServer = "" then
        exit sub
    endif

    Rem Ask the user for a user name
    sUser = InputBox("Please enter a user name", _
                     "Test NextCloud Discovery URL")
    Rem User clicked Cancel
    if sUser = "" then
        exit sub
    endif

    Rem Ask the user for a Username
    sPassword = InputBox("Please enter a user password", _
                         "Test NextCloud Discovery URL")
    Rem User clicked Cancel
    if sPassword = "" then
        exit sub
    endif

    Rem To execute an HTTP request we first need a HTTP Request parameter
    oParameter = oRequest.getRequestParameter("nextcloud")

    Rem Default Requests method is GET and must be changed
    oParameter.Method = "PROPFIND"

    Rem Normally a CardDAV server (ie: NextCloud) should respond
    Rem on the address: /.well-known/carddav
    oParameter.Url = "https://" & sServer & "/.well-known/carddav"

    Rem Defining all the properties needed to get the Discovery URL
    oParameter.Auth = Array(sUser, sPassword)
    oParameter.setHeader("Content-Type", "application/xml; charset=utf-8")
    oParameter.setHeader("Depth", "0")
    oParameter.NoRedirect = True

    Rem To obtain the HTTP response we use the execute() method
    Rem of the OAuth2Service service with the HTTP parameter as argument
    oResponse = oRequest.execute(oParameter)

    if oResponse.Ok then
        if oResponse.hasHeader("Location") then
            sText = "Discovery URL: " & oResponse.getHeader("Location")
        else
            sText = "ERROR: not a redirect (ie: Response has no Location header) " & oResponse.Text
        endif
    else
        sText = "ERROR: HTTP status code error: " & oResponse.StatusCode & " Response text: " & oResponse.Text
    endif

    Rem When it is finished we have to close the HTTP response
    oResponse.close()

    Msgbox sText

End Sub
```

You can create a new macro and copy the code into it.
If I run the macro I get the message:

![Discovery url](https://github.com/user-attachments/assets/848d3ad8-5eea-4e27-bd76-45a73a7c1307)

**Comment by ralfrupf1976** [comment]
![Bildschirmfoto_20241011_163009](https://github.com/user-attachments/assets/975d026a-2ab8-4bbd-b7e0-db05b567252e)

**Comment by ralfrupf1976** [comment]
I used your macro and it results in the screen above

**Comment by ralfrupf1976** [comment]
But it's still not possible to connect to nextcloud using vcards

**Comment by prrvchr** [comment]
the latest version of the macro (it has been updated several times) must be more complete than the one you tried.

Please give me the error messages with the latest version of the macro.

**Comment by ralfrupf1976** [comment]
My Nextcloud ist behind Nginx Proxy Manager in advanced I added:

    location = /.well-known/carddav {
      return 301 $scheme://$host:$server_port/remote.php/dav;
    }
    location = /.well-known/caldav {
      return 301 $scheme://$host:$server_port/remote.php/dav;
    }

For testing I started from scratch:
Windows 11
Latest LibreOffice 24.8.2
Java Version 8 Update 421 (Build 1.8.0_421-b09)
Latest Version from Extensions from here: https://github.com/prrvchr/vCardOOo/

If I try to install the jdbcDriverOOo - it crashes:

(com.sun.star.uno.RuntimeException) { { Message = "[jni_uno bridge error] UNO calling Java method writeRegistryInfo: non-UNO exception occurred: java.lang.UnsupportedClassVersionError: io/github/prrvchr/jdbcdriver/RegistrationHandler has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0\X000ajava stack trace:\X000ajava.lang.UnsupportedClassVersionError: io/github/prrvchr/jdbcdriver/RegistrationHandler has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0\X000d\X000a\X0009at java.lang.ClassLoader.defineClass1(Native Method)\X000d\X000a\X0009at java.lang.ClassLoader.defineClass(Unknown Source)\X000d\X000a\X0009at java.security.SecureClassLoader.defineClass(Unknown Source)\X000d\X000a\X0009at java.net.URLClassLoader.defineClass(Unknown Source)\X000d\X000a\X0009at java.net.URLClassLoader.access$100(Unknown Source)\X000d\X000a\X0009at java.net.URLClassLoader$1.run(Unknown Source)\X000d\X000a\X0009at java.net.URLClassLoader$1.run(Unknown Source)\X000d\X000a\X0009at java.security.AccessController.doPrivileged(Native Method)\X000d\X000a\X0009at java.net.URLClassLoader.findClass(Unknown Source)\X000d\X000a\X0009at java.lang.ClassLoader.loadClass(Unknown Source)\X000d\X000a\X0009at java.lang.ClassLoader.loadClass(Unknown Source)\X000d\X000a\X0009at java.net.FactoryURLClassLoader.loadClass(Unknown Source)\X000d\X000a\X0009at java.lang.ClassLoader.loadClass(Unknown Source)\X000d\X000a\X0009at com.sun.star.comp.loader.RegistrationClassFinder.find(RegistrationClassFinder.java:53)\X000d\X000a\X0009at com.sun.star.comp.loader.JavaLoader.writeRegistryInfo(JavaLoader.java:376)\X000d\X000a", Context = (com.sun.star.uno.XInterface) @0 } }

**Comment by prrvchr** [comment]
> Java Version 8 Update 421 (Build 1.8.0_421-b09)

Java 8 just celebrated its 20th anniversary. **No, it's Java 11 minimum**.

**Comment by ralfrupf1976** [comment]
I got it up and running: Setting Proxmox, LXC, Docker, Nextcloud behind nginx proxy manager!

I had to paste the above code in the advanced settings of nginx:

```
location = /.well-known/carddav {
  return 301 $scheme://$host:$server_port/remote.php/dav;
}
location = /.well-known/caldav {
  return 301 $scheme://$host:$server_port/remote.php/dav;
}
```
Java... the documentation on libreoffice is a bit unclear. Yes, now with Java 23 its running.

First I found [this](https://wiki.documentfoundation.org/Faq/General/InstallJava)

Now with java from [here ](https://www.oracle.com/ch-de/java/technologies/downloads/)it works

Quit a little pain to make everything work. But thank you for your great work and support

**Comment by prrvchr** [comment]
> First I found [this](https://wiki.documentfoundation.org/Faq/General/InstallJava)

Maybe this explanation is a bit better: [Install the correct JRE - LibreOffice on Windows 10 / 11](https://wiki.documentfoundation.org/Documentation/HowTo/Install_the_correct_JRE_-_LibreOffice_on_Windows_10)

> Now with java from [here ](https://www.oracle.com/ch-de/java/technologies/downloads/)it works

As it is said in the [requirements of jdbcDriverOOo](https://prrvchr.github.io/jdbcDriverOOo/#requirement) I advise to install from [Adoptium](https://adoptium.net/releases.html?variant=openjdk11)

> Quit a little pain to make everything work. But thank you for your great work and support

You are welcome and I am glad to know that it works behind a proxy.

Ok I close
